//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_VENDAS.VIEW.CFuncionarioWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/MVC_VENDAS.MODEL")]
    [System.SerializableAttribute()]
    public partial class Funcionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CFuncionarioWCF.ICFuncionario")]
    public interface ICFuncionario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/ListaFuncionarios", ReplyAction="http://tempuri.org/ICFuncionario/ListaFuncionariosResponse")]
        MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario[] ListaFuncionarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/ListaFuncionarios", ReplyAction="http://tempuri.org/ICFuncionario/ListaFuncionariosResponse")]
        System.Threading.Tasks.Task<MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario[]> ListaFuncionariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/AlterarFuncionario", ReplyAction="http://tempuri.org/ICFuncionario/AlterarFuncionarioResponse")]
        void AlterarFuncionario(MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/AlterarFuncionario", ReplyAction="http://tempuri.org/ICFuncionario/AlterarFuncionarioResponse")]
        System.Threading.Tasks.Task AlterarFuncionarioAsync(MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/SelecionarFuncionario", ReplyAction="http://tempuri.org/ICFuncionario/SelecionarFuncionarioResponse")]
        MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario SelecionarFuncionario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/SelecionarFuncionario", ReplyAction="http://tempuri.org/ICFuncionario/SelecionarFuncionarioResponse")]
        System.Threading.Tasks.Task<MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario> SelecionarFuncionarioAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/ExcluirFuncionario", ReplyAction="http://tempuri.org/ICFuncionario/ExcluirFuncionarioResponse")]
        void ExcluirFuncionario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/ExcluirFuncionario", ReplyAction="http://tempuri.org/ICFuncionario/ExcluirFuncionarioResponse")]
        System.Threading.Tasks.Task ExcluirFuncionarioAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/IncluirFuncionario", ReplyAction="http://tempuri.org/ICFuncionario/IncluirFuncionarioResponse")]
        void IncluirFuncionario(MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/IncluirFuncionario", ReplyAction="http://tempuri.org/ICFuncionario/IncluirFuncionarioResponse")]
        System.Threading.Tasks.Task IncluirFuncionarioAsync(MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario oFuncionario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICFuncionarioChannel : MVC_VENDAS.VIEW.CFuncionarioWCF.ICFuncionario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFuncionarioClient : System.ServiceModel.ClientBase<MVC_VENDAS.VIEW.CFuncionarioWCF.ICFuncionario>, MVC_VENDAS.VIEW.CFuncionarioWCF.ICFuncionario {
        
        public CFuncionarioClient() {
        }
        
        public CFuncionarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFuncionarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFuncionarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFuncionarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario[] ListaFuncionarios() {
            return base.Channel.ListaFuncionarios();
        }
        
        public System.Threading.Tasks.Task<MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario[]> ListaFuncionariosAsync() {
            return base.Channel.ListaFuncionariosAsync();
        }
        
        public void AlterarFuncionario(MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario oFuncionario) {
            base.Channel.AlterarFuncionario(oFuncionario);
        }
        
        public System.Threading.Tasks.Task AlterarFuncionarioAsync(MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario oFuncionario) {
            return base.Channel.AlterarFuncionarioAsync(oFuncionario);
        }
        
        public MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario SelecionarFuncionario(int Codigo) {
            return base.Channel.SelecionarFuncionario(Codigo);
        }
        
        public System.Threading.Tasks.Task<MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario> SelecionarFuncionarioAsync(int Codigo) {
            return base.Channel.SelecionarFuncionarioAsync(Codigo);
        }
        
        public void ExcluirFuncionario(int Codigo) {
            base.Channel.ExcluirFuncionario(Codigo);
        }
        
        public System.Threading.Tasks.Task ExcluirFuncionarioAsync(int Codigo) {
            return base.Channel.ExcluirFuncionarioAsync(Codigo);
        }
        
        public void IncluirFuncionario(MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario oFuncionario) {
            base.Channel.IncluirFuncionario(oFuncionario);
        }
        
        public System.Threading.Tasks.Task IncluirFuncionarioAsync(MVC_VENDAS.VIEW.CFuncionarioWCF.Funcionario oFuncionario) {
            return base.Channel.IncluirFuncionarioAsync(oFuncionario);
        }
    }
}
