//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_VENDAS.VIEW.CVendasWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CVendasWCF.ICVendas")]
    public interface ICVendas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICVendas/ListaVendas", ReplyAction="http://tempuri.org/ICVendas/ListaVendasResponse")]
        MVC_VENDAS.MODEL.Venda[] ListaVendas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICVendas/ListaVendas", ReplyAction="http://tempuri.org/ICVendas/ListaVendasResponse")]
        System.Threading.Tasks.Task<MVC_VENDAS.MODEL.Venda[]> ListaVendasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICVendas/SelecionarVenda", ReplyAction="http://tempuri.org/ICVendas/SelecionarVendaResponse")]
        MVC_VENDAS.MODEL.Venda SelecionarVenda(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICVendas/SelecionarVenda", ReplyAction="http://tempuri.org/ICVendas/SelecionarVendaResponse")]
        System.Threading.Tasks.Task<MVC_VENDAS.MODEL.Venda> SelecionarVendaAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICVendas/IncluirVenda", ReplyAction="http://tempuri.org/ICVendas/IncluirVendaResponse")]
        int IncluirVenda(MVC_VENDAS.MODEL.Venda oVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICVendas/IncluirVenda", ReplyAction="http://tempuri.org/ICVendas/IncluirVendaResponse")]
        System.Threading.Tasks.Task<int> IncluirVendaAsync(MVC_VENDAS.MODEL.Venda oVenda);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICVendasChannel : MVC_VENDAS.VIEW.CVendasWCF.ICVendas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CVendasClient : System.ServiceModel.ClientBase<MVC_VENDAS.VIEW.CVendasWCF.ICVendas>, MVC_VENDAS.VIEW.CVendasWCF.ICVendas {
        
        public CVendasClient() {
        }
        
        public CVendasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CVendasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CVendasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CVendasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_VENDAS.MODEL.Venda[] ListaVendas() {
            return base.Channel.ListaVendas();
        }
        
        public System.Threading.Tasks.Task<MVC_VENDAS.MODEL.Venda[]> ListaVendasAsync() {
            return base.Channel.ListaVendasAsync();
        }
        
        public MVC_VENDAS.MODEL.Venda SelecionarVenda(int Codigo) {
            return base.Channel.SelecionarVenda(Codigo);
        }
        
        public System.Threading.Tasks.Task<MVC_VENDAS.MODEL.Venda> SelecionarVendaAsync(int Codigo) {
            return base.Channel.SelecionarVendaAsync(Codigo);
        }
        
        public int IncluirVenda(MVC_VENDAS.MODEL.Venda oVenda) {
            return base.Channel.IncluirVenda(oVenda);
        }
        
        public System.Threading.Tasks.Task<int> IncluirVendaAsync(MVC_VENDAS.MODEL.Venda oVenda) {
            return base.Channel.IncluirVendaAsync(oVenda);
        }
    }
}
