//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_VENDAS.VIEW.CProdutoWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/MVC_VENDAS.MODEL")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PercLucroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QtdEstoqueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PercLucro {
            get {
                return this.PercLucroField;
            }
            set {
                if ((this.PercLucroField.Equals(value) != true)) {
                    this.PercLucroField = value;
                    this.RaisePropertyChanged("PercLucro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoCompra {
            get {
                return this.PrecoCompraField;
            }
            set {
                if ((this.PrecoCompraField.Equals(value) != true)) {
                    this.PrecoCompraField = value;
                    this.RaisePropertyChanged("PrecoCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QtdEstoque {
            get {
                return this.QtdEstoqueField;
            }
            set {
                if ((this.QtdEstoqueField.Equals(value) != true)) {
                    this.QtdEstoqueField = value;
                    this.RaisePropertyChanged("QtdEstoque");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CProdutoWCF.ICProduto")]
    public interface ICProduto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/ListaProdutos", ReplyAction="http://tempuri.org/ICProduto/ListaProdutosResponse")]
        MVC_VENDAS.VIEW.CProdutoWCF.Produto[] ListaProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/ListaProdutos", ReplyAction="http://tempuri.org/ICProduto/ListaProdutosResponse")]
        System.Threading.Tasks.Task<MVC_VENDAS.VIEW.CProdutoWCF.Produto[]> ListaProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/IncluirProduto", ReplyAction="http://tempuri.org/ICProduto/IncluirProdutoResponse")]
        void IncluirProduto(MVC_VENDAS.VIEW.CProdutoWCF.Produto oProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/IncluirProduto", ReplyAction="http://tempuri.org/ICProduto/IncluirProdutoResponse")]
        System.Threading.Tasks.Task IncluirProdutoAsync(MVC_VENDAS.VIEW.CProdutoWCF.Produto oProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/AlterarProduto", ReplyAction="http://tempuri.org/ICProduto/AlterarProdutoResponse")]
        void AlterarProduto(MVC_VENDAS.VIEW.CProdutoWCF.Produto oProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/AlterarProduto", ReplyAction="http://tempuri.org/ICProduto/AlterarProdutoResponse")]
        System.Threading.Tasks.Task AlterarProdutoAsync(MVC_VENDAS.VIEW.CProdutoWCF.Produto oProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/SelecionarProduto", ReplyAction="http://tempuri.org/ICProduto/SelecionarProdutoResponse")]
        MVC_VENDAS.VIEW.CProdutoWCF.Produto SelecionarProduto(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/SelecionarProduto", ReplyAction="http://tempuri.org/ICProduto/SelecionarProdutoResponse")]
        System.Threading.Tasks.Task<MVC_VENDAS.VIEW.CProdutoWCF.Produto> SelecionarProdutoAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/ExcluirProduto", ReplyAction="http://tempuri.org/ICProduto/ExcluirProdutoResponse")]
        void ExcluirProduto(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICProduto/ExcluirProduto", ReplyAction="http://tempuri.org/ICProduto/ExcluirProdutoResponse")]
        System.Threading.Tasks.Task ExcluirProdutoAsync(string Codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICProdutoChannel : MVC_VENDAS.VIEW.CProdutoWCF.ICProduto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CProdutoClient : System.ServiceModel.ClientBase<MVC_VENDAS.VIEW.CProdutoWCF.ICProduto>, MVC_VENDAS.VIEW.CProdutoWCF.ICProduto {
        
        public CProdutoClient() {
        }
        
        public CProdutoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CProdutoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CProdutoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CProdutoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_VENDAS.VIEW.CProdutoWCF.Produto[] ListaProdutos() {
            return base.Channel.ListaProdutos();
        }
        
        public System.Threading.Tasks.Task<MVC_VENDAS.VIEW.CProdutoWCF.Produto[]> ListaProdutosAsync() {
            return base.Channel.ListaProdutosAsync();
        }
        
        public void IncluirProduto(MVC_VENDAS.VIEW.CProdutoWCF.Produto oProduto) {
            base.Channel.IncluirProduto(oProduto);
        }
        
        public System.Threading.Tasks.Task IncluirProdutoAsync(MVC_VENDAS.VIEW.CProdutoWCF.Produto oProduto) {
            return base.Channel.IncluirProdutoAsync(oProduto);
        }
        
        public void AlterarProduto(MVC_VENDAS.VIEW.CProdutoWCF.Produto oProduto) {
            base.Channel.AlterarProduto(oProduto);
        }
        
        public System.Threading.Tasks.Task AlterarProdutoAsync(MVC_VENDAS.VIEW.CProdutoWCF.Produto oProduto) {
            return base.Channel.AlterarProdutoAsync(oProduto);
        }
        
        public MVC_VENDAS.VIEW.CProdutoWCF.Produto SelecionarProduto(string Codigo) {
            return base.Channel.SelecionarProduto(Codigo);
        }
        
        public System.Threading.Tasks.Task<MVC_VENDAS.VIEW.CProdutoWCF.Produto> SelecionarProdutoAsync(string Codigo) {
            return base.Channel.SelecionarProdutoAsync(Codigo);
        }
        
        public void ExcluirProduto(string Codigo) {
            base.Channel.ExcluirProduto(Codigo);
        }
        
        public System.Threading.Tasks.Task ExcluirProdutoAsync(string Codigo) {
            return base.Channel.ExcluirProdutoAsync(Codigo);
        }
    }
}
